name: Smart Slack Alert

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Test
        run: |
          echo "Running test..."
          exit 0   # change to 1 for fail

      - name: Send Success Alert
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\":\"✅ Build Passed\n📦 Repo: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\n👤 Triggered by: ${{ github.actor }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Failure Alert
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\":\"❌ Build Failed\n📦 Repo: ${{ github.repository }}\n🌿 Branch: ${{ github.ref_name }}\n👤 Triggered by: ${{ github.actor }}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
