name: Smart Slack Alert

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate Test
        id: test_step
        run: |
          echo "Running test..."
          exit 0   # change to 1 for fail

      - name: Send Success Alert
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ GitHub Action Passed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Failure Alert
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ GitHub Action Failed!"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
